import 'package:hive_flutter/hive_flutter.dart';
import '../models/gift_card.dart';

class StorageService {
  static const String _settingsBoxName = 'settings';
  static const String _giftCardsBoxName = 'giftcards';
  static const String _balanceKey = 'balance';

  late Box _settingsBox;
  late Box<RedeemedGiftCard> _giftCardsBox;

  Future<void> init() async {
    await Hive.initFlutter();
    
    // Adapters must be registered before opening boxes
    // Note: Adapters are generated by build_runner in gift_card.g.dart
    Hive.registerAdapter(GiftCardOptionAdapter());
    Hive.registerAdapter(RedeemedGiftCardAdapter());

    _settingsBox = await Hive.openBox(_settingsBoxName);
    _giftCardsBox = await Hive.openBox<RedeemedGiftCard>(_giftCardsBoxName);
  }

  // Balance Operations
  Future<void> saveBalance(int balance) async {
    await _settingsBox.put(_balanceKey, balance);
  }

  int getBalance() {
    return _settingsBox.get(_balanceKey, defaultValue: 0);
  }

  // GiftCard Operations
  Future<void> saveGiftCard(RedeemedGiftCard giftCard) async {
    await _giftCardsBox.put(giftCard.id, giftCard);
  }

  List<RedeemedGiftCard> getGiftCards() {
    return _giftCardsBox.values.toList()
      ..sort((a, b) => b.dateRedeemed.compareTo(a.dateRedeemed));
  }
  
  Future<void> clearAll() async {
    await _settingsBox.clear();
    await _giftCardsBox.clear();
  }
}
